### ISSUE TITLE
Read only calls ignoring blockNumber override

### ISSUE THREAD

**Issue by 0xleez** [0xOlias/ponder#196]
All the read-only calls get the latest answer from the contract instead of the result at the time of the event.

It looks like the overrides don't get passed to the `readContract` function when caching is enabled?
https://github.com/0xOlias/ponder/blob/828cb48784e627c0d370631cbf65870a2fed4c52/packages/core/src/handlers/buildInjectedContract.ts#L98

**Comment by 0xOlias** [comment]
Hi @0xleez, thanks for reporting! I was able to repro this issue, and it should be fixed in 0.0.60.

I ended up overhauling the contract instance approach entirely, and added a test case to confirm that this behavior works as intended. If you're curious, [here's the new approach](https://github.com/0xOlias/ponder/blob/50571b64c2feb8f7e9fdd36d77625ca5c5162d38/packages/core/src/user-handlers/contract.ts).
