### ISSUE TITLE
[Bug] Requests made before sync happens do not result in an error

### ISSUE THREAD

**Issue by Willyham** [0xOlias/ponder#347]
Hey, we encountered an issue where Ponder restarted, and as it was coming back online, it had some issues syncing due to instability with our RPC provider.

```
> start
> ponder start
22:09:28.477 DEBUG app        Started using config file: ponder.config.ts
22:09:28.484 INFO  server     Started listening on port 6086
22:09:29.008 DEBUG codegen    Wrote new file at generated/index.ts
22:09:29.352 DEBUG codegen    Wrote new file at generated/index.ts
22:09:29.392 DEBUG codegen    Wrote new file at generated/schema.graphql
22:09:29.418 DEBUG handlers   Paused event queue (versionId=undefined)
22:09:29.591 DEBUG handlers   Reset user store (versionId=e601b59f)
22:09:35.110 INFO  realtime   Fetched latest block at 9689903 (network=goerli)
22:09:35.295 INFO  historical Started sync with 100% cached (logFilter=Staking network=goerli)
22:09:35.421 INFO  historical Started sync with 100% cached (logFilter=Oracle network=goerli)
22:09:36.176 INFO  realtime   Fetched finalized block at 9689871 (network=goerli)
22:09:44.216 ERROR historical Log sync task failed (network=goerli, logFilter=Staking)
HttpRequestError: HTTP request failed.
Status: 503
URL: https://eth-goerli.g.alchemy.com/v2/foo
Request body: {"method":"eth_getLogs","params":[{"address":"0x72e6a6d798be85157f4ec8d71444cdd2a7612d3d","fromBlock":"0x93daf4","toBlock":"0x93db0f"}]}
Details: {"code":-32000,"message":"Unable to complete request at this time."}
Version: viem@1.5.4
```

This is expected, and ponder did the correct thing of retrying until it was able to sync ✨. However, in the period between `22:09:36` where the finalized block was loaded, and `22:09:44` where the sync failed, ponder was serving results with incorrect values.

One of our services was made a request to load events at `22:09:37`, and ponder responded with `0` events found. This threw off our service as it was an unexpected result. 

I think the correct behaviour in this case is to always return an error until the sync has completed, as the events are unknown rather than known to be empty.

**Comment by 0xOlias** [comment]
Thanks for the well-researched bug report @Willyham!

As you might know, Ponder is designed to only respond as healthy (via a `200` status code at the `/health` path) _after_ al logs from the historical period have been indexed. This is the mechanism that enables zero-downtime deployments. Based on the logs you shared, it looks like historical indexing was not complete. If it were, we would see logs like:
```
INFO historical Completed sync
INFO server     Started responding as healthy
```
Nonetheless, one of your services still made a request to the GraphQL API. I can think of two ways this could happen:
1) You have not set the healthcheck path in your hosting environment, so zero-downtime deployments are not enabled.
2) Ponder has a bug where it is responding as healthy before the historical sync is complete (and before those two log lines are produced). Your hosting provider got a `200` from the new instance, marked it as healthy, and routed the request to it (but it was not actually ready).

Clarifying questions for you:
1) What environment/hosting provider are you running Ponder on?
2) If using a platform like Railway, have you set the healthcheck path in the service config?

That aside, you bring up an interesting question - should the GraphQL API also return errors if historical indexing is not complete? At the moment, the GraphQL API always works even though it can silently return incomplete/incorrect data. I have found this useful during development to run queries against the server while historical indexing is still in progress. IMO, the healthcheck path should be relied up for this rather than the GraphQL API, but open to challenge on that. It also could behave differently for `ponder dev` and `ponder start`.

**Comment by Willyham** [comment]
Thanks for the explanation and background. This deployment is on railway and a health check is set. This was not a deploy, but a crash-loop when HTTP requests to the RPC provider were failing (we have since upgraded to 0.88 which I think solves that issue?). In this case, there was only once instance so I'm guessing Railway continues to try to route requests as best it can.

> IMO, the healthcheck path should be relied up for this rather than the GraphQL API, but open to challenge on that.

My impression is that the health check is essentially an internal detail, and external services which are querying data should not need to know about it or rely on it. Otherwise, we'd need to query `/health` before every graphql query to ensure that we are getting the correct data.

I think that there are too many different deployment/failure recovery scenarios to rely on a provider _never_ routing to an instance which isn't healthy. And if that is true, I think Ponder should always prefer to make the decision to return data which is "reliable or nothing".

I think most people are probably using Ponder for web queries where maybe the importance of being accurate is lower (someone can just refresh I guess) - we're using it for that too, but we also use it to do some sanity/reconciliation checks to determine if the protocol is operating properly. In these cases, we may alert people or even pause the protocol if we see discrepancies. So, if we get an error back, we know that Ponder isn't ready yet, and we can handle that case by backing off and retrying. If we get a 200 but with wrong data, we have no way of knowing that Ponder is still syncing (unless we were to call /health before every query as I mentioned before).

**Comment by 0xOlias** [comment]
Thanks again, this is helpful. Didn't realize it was on a crash (sorry that happened!).

Very well-reasoned. What do you think about the suggestion of treating`ponder start` and `ponder dev` differently?

- `ponder start` - Return 4xx errors from the GraphQL endpoint whenever the service is not healthy (treat `/` the same as `/health`).
- `ponder dev` - Serve GraphQL requests even when the service is not healthy

Alternatively, we could make this configurable in `ponder.config.ts` or via env var, but I feel like this is a reasonable default and would rather not add an option.
